### ISSUE TITLE
Use cases for separate language and direction metadata

### ISSUE THREAD

**Issue by aphillips** [w3c/rdf-dir-literal#6] opened 2019-05-29 16:04 UTC
Side thoughts not expressed in the call. There was some question about whether we need direction at all. I think it is helpful to summarize the use cases. I think these might be:

1. Strings with *NO* language and *NO* direction metadata.
* Best Practice: display in an isolating context; use "first strong" semantics
* NOTE: this includes data strings such as MAC addresses, ISBNs, etc.
2. Strings with language metadata but *NO* direction metadata.
* Best Practice: display in an isolating context; estimate direction from the language tag.
3. Strings with *BOTH* language and direction metadata.
* Best Practice: display in an isolating context; use direction metadata for base direction.
4. Strings with direction metadata and *NO* language metadata (or an indeterminate language such as `und`)
* Best Practice: display in an isolating context; use direction metadata

3 and 4 are unsolved problems in the Linked Data space and what (I think) we're discussing here. A key problem is that language estimation, particularly for short strings, is difficult and relies on flawed heuristics or on contextual data. There exist many contexts in which the customer's experienced based direction can be determined but where language metadata is harder to obtain. This is particularly true of UGC on the Web.

Would it help to write realistic user scenarios?

_Originally posted by @aphillips in https://github.com/w3c/rdf-dir-literal/issues/3#issuecomment-496994496_

**Comment by iherman** [comment] 2019-05-29 16:12
Closing... duplicate of #7

**Closed as completed by iherman** 2019-05-29 16:12 UTC
